"""Write docs/LIBRARY.md, a browsable index of every motif in the library."""

import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from motif.interpreter import make_interpreter          # noqa: E402
from motif.motifs.registry import REGISTRY, categories  # noqa: E402
from motif.motifs.restriction import overhang           # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "LIBRARY.md")

interp = make_interpreter()
interp.eval_source("(use-library 'all)")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
by_source: dict[str, list] = {}
for e in REGISTRY.values():
    by_source.setdefault(e.source or "other", []).append(e)

ORDER = ["prokaryote.mtf", "eukaryote.mtf", "plant.mtf", "rna.mtf",
         "protein.mtf", "tags.mtf", "restriction.mtf"]
TITLES = {
    "prokaryote.mtf": "Bacterial and archaeal elements",
    "eukaryote.mtf": "Animal and fungal elements",
    "plant.mtf": "Plant cis-regulatory elements",
    "rna.mtf": "RNA elements",
    "protein.mtf": "Protein motifs",
    "tags.mtf": "Tags, vectors and laboratory sequences",
    "restriction.mtf": "Restriction enzymes",
}


def clean(text: str) -> str:
    return " ".join(text.split())


with open(OUT, "w") as f:
    f.write("# The motif library\n\n")
    f.write(f"{len(REGISTRY)} motifs in {len(categories())} categories. ")
    f.write("Generated by `python tools/make_index.py`; edit the `.mtf` files, not this page.\n\n")
    f.write("A motif marked *template* matches almost anywhere and is skipped by "
            "`scan` unless you pass `:all #t`. Search for it by name instead.\n\n")

    f.write("## Contents\n\n")
    for src in ORDER:
        entries = by_source.get(src, [])
        f.write(f"- [{TITLES[src]}](#{TITLES[src].lower().replace(' ', '-')}) "
                f"&mdash; {len(entries)} motifs\n")
    f.write("\n")

    for src in ORDER:
        group = by_source.get(src, [])
        if not group:
            continue
        f.write(f"## {TITLES[src]}\n\n")
        f.write(f"Defined in `motif/lib/{src}`.\n\n")

        if src == "restriction.mtf":
            enzymes = sorted((e for e in group if e.meta.get("site")), key=lambda e: e.name.lower())
            f.write("| Enzyme | Site | Cut | Ends |\n|---|---|---|---|\n")
            for e in enzymes:
                site = e.meta["site"]
                top, bottom = e.meta["cut_top"], e.meta["cut_bottom"]
                marked = site[:top] + "^" + site[top:] if 0 <= top <= len(site) else f"{site}({top}/{bottom})"
                f.write(f"| `{e.name}` | `{site}` | `{marked}` | {overhang(e.meta)} |\n")
            others = [e for e in group if not e.meta.get("site")]
            if others:
                f.write("\n### Methylation and modification sites\n\n")
                for e in sorted(others, key=lambda e: e.name):
                    f.write(f"**`{e.name}`** &mdash; {clean(e.doc)}\n\n")
            f.write("\n")
            continue

        for cat in sorted({e.category for e in group}):
            f.write(f"### {cat}\n\n")
            for e in sorted((x for x in group if x.category == cat), key=lambda e: e.name):
                flag = " *(template)*" if not e.scan else ""
                f.write(f"**`{e.name}`**{flag}\n\n")
                for line in textwrap.wrap(clean(e.doc), 92):
                    f.write(line + "\n")
                f.write("\n")
                f.write(f"- pattern: `{e.matcher.describe()}`\n")
                if e.example:
                    f.write(f"- example: `{e.example}`\n")
                if e.ref:
                    f.write(f"- reference: {e.ref}\n")
                f.write("\n")
        f.write("\n")

print(f"{OUT}  {len(REGISTRY)} motifs")
