/* Write docs/LIBRARY.md, a browsable index of every motif in the library.
   Generated by `npm run index`; edit the .mtf files, not that page. */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { Registry, loadLibrarySource, overhang } from "../web/src/library.js";
import { LIB_FILES } from "./build.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "docs", "LIBRARY.md");

const TITLES = {
  "prokaryote.mtf": "Bacterial and archaeal elements",
  "eukaryote.mtf": "Animal and fungal elements",
  "plant.mtf": "Plant cis-regulatory elements",
  "rna.mtf": "RNA elements",
  "protein.mtf": "Protein motifs",
  "tags.mtf": "Tags, vectors and laboratory sequences",
  "restriction.mtf": "Restriction enzymes",
};
const ORDER = LIB_FILES.map((n) => `${n}.mtf`);

const registry = new Registry();
for (const name of LIB_FILES) {
  loadLibrarySource(`${name}.mtf`, readFileSync(join(ROOT, "library", `${name}.mtf`), "utf8"), registry);
}

const bySource = new Map();
for (const e of registry.all()) {
  if (!bySource.has(e.source)) bySource.set(e.source, []);
  bySource.get(e.source).push(e);
}

const anchor = (title) => title.toLowerCase().replace(/[^a-z0-9 ]/g, "").replace(/ /g, "-");
const byName = (a, b) => (a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1);

function wrap(text, width = 92) {
  const words = text.split(/\s+/);
  const lines = [];
  let line = "";
  for (const w of words) {
    if (line && line.length + w.length + 1 > width) { lines.push(line); line = w; }
    else line = line ? `${line} ${w}` : w;
  }
  if (line) lines.push(line);
  return lines;
}

const out = [];
out.push("# The motif library\n");
out.push(`${registry.size} motifs in ${registry.categories().length} categories. ` +
  "Generated by `npm run index`; edit the `.mtf` files, not this page.\n");
out.push("A motif marked *template* matches almost anywhere and is skipped by `scan` " +
  "unless you pass `:all #t`. Search for it by name instead.\n");
out.push("## Contents\n");
for (const src of ORDER) {
  out.push(`- [${TITLES[src]}](#${anchor(TITLES[src])}) &mdash; ${(bySource.get(src) ?? []).length} motifs`);
}
out.push("");

for (const src of ORDER) {
  const group = bySource.get(src) ?? [];
  if (!group.length) continue;
  out.push(`## ${TITLES[src]}\n`);
  out.push(`Defined in \`library/${src}\`.\n`);

  if (src === "restriction.mtf") {
    const enzymes = group.filter((e) => e.meta).sort(byName);
    out.push("| Enzyme | Site | Cut | Ends |");
    out.push("|---|---|---|---|");
    for (const e of enzymes) {
      const { site, cutTop, cutBottom } = e.meta;
      const marked = cutTop >= 0 && cutTop <= site.length
        ? site.slice(0, cutTop) + "^" + site.slice(cutTop)
        : `${site}(${cutTop}/${cutBottom})`;
      out.push(`| \`${e.name}\` | \`${site}\` | \`${marked}\` | ${overhang(e.meta)} |`);
    }
    const others = group.filter((e) => !e.meta).sort(byName);
    if (others.length) {
      out.push("\n### Methylation and modification sites\n");
      for (const e of others) out.push(`**\`${e.name}\`** &mdash; ${e.doc}\n`);
    }
    out.push("");
    continue;
  }

  for (const cat of [...new Set(group.map((e) => e.category))].sort()) {
    out.push(`### ${cat}\n`);
    for (const e of group.filter((x) => x.category === cat).sort(byName)) {
      out.push(`**\`${e.name}\`**${e.scan ? "" : " *(template)*"}\n`);
      out.push(...wrap(e.doc), "");
      out.push(`- pattern: \`${e.pattern}\``);
      if (e.example) out.push(`- example: \`${e.example}\``);
      if (e.ref) out.push(`- reference: ${e.ref}`);
      out.push("");
    }
  }
  out.push("");
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out.join("\n"));
console.log(`  docs/LIBRARY.md  ${registry.size} motifs, ${out.length} lines`);
